name: Compile MakeMKV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config qt5-qmake qtbase5-dev \
                                libavcodec-dev libavutil-dev libavformat-dev \
                                zlib1g-dev libexpat1-dev libssl-dev fuse squashfs-tools wget \
                                libc6-dev

    - name: Download MakeMKV source files
      run: |
        # Define URL to check for the latest version
        MAKEMKV_URL="https://forum.makemkv.com/forum/viewtopic.php?f=3&t=224"

        # Define function to download the latest MakeMKV
        get_makemkv() {
          local _dir="$1"
          [ "" == "$_dir" ] && _dir='.'
          local _PAGE=$(timeout -k 0 30 wget -qO - "$MAKEMKV_URL")
          local _BIN=$(printf "%s" "$_PAGE" | grep -io 'https://www.makemkv.com/download/makemkv-bin-[^"]*' | head -n 1)
          local _OSS=$(printf "%s" "$_PAGE" | grep -io 'https://www.makemkv.com/download/makemkv-oss-[^"]*' | head -n 1)
          if [ "" != "$_BIN" ] && [ "" != "$_OSS" ]; then
            wget -O "$_dir/$(basename "$_BIN")" "$_BIN" || return 1
            wget -O "$_dir/$(basename "$_OSS")" "$_OSS" || return 1
            return 0
          fi
          return 1
        }

        # Run the function to download MakeMKV
        get_makemkv "$PWD"

    - name: Extract and build MakeMKV
      run: |
        # Extract the source packages
        tar -xzf makemkv-oss-*.tar.gz
        tar -xzf makemkv-bin-*.tar.gz

        # Find and enter the extracted directories for OSS and Bin
        OSS_DIR=$(find . -maxdepth 1 -type d -name "makemkv-oss-*")
        BIN_DIR=$(find . -maxdepth 1 -type d -name "makemkv-bin-*")
        
        if [ -z "$OSS_DIR" ] || [ -z "$BIN_DIR" ]; then
          echo "Error: Required directories not found"
          exit 1
        fi

        # Build OSS package
        cd "$OSS_DIR"
        ./configure
        make
        sudo make install
        cd ..

        # Build binary package
        cd "$BIN_DIR"
        # Automatically accept the EULA before proceeding
        echo "yes" | make
        sudo make install
        cd ..

    - name: Clean up
      run: |
        # Remove downloaded source files to save space
        rm -rf makemkv-oss-* makemkv-bin-*
